language: php
sudo: false
php:
- 5.6
- 7.0
- 7.1
- 7.2
- 7.3
matrix:
  fast_finish: true
  exclude:
  - php: 5.3
    env: DRUPAL_TI_RUNNERS="test phpunit phpunit-core simpletest behat" DRUPAL_TI_SAVE_CACHE="0"
  - php: 5.4
    env: DRUPAL_TI_RUNNERS="test phpunit phpunit-core simpletest behat" DRUPAL_TI_SAVE_CACHE="0"
  - php: 5.5
env:
  global:
  - PATH="$HOME/.composer/vendor/bin:$PATH"
  - DRUPAL_TI_MODULE_NAME="sendgrid_integration"
  - DRUPAL_TI_SIMPLETEST_GROUP="Sendgrid Integration"
  - DRUPAL_TI_ENVIRONMENT="drupal-7"
  - DRUPAL_TI_DB="drupal_travis_db"
  - DRUPAL_TI_DB_URL="mysql://root:@127.0.0.1/drupal_travis_db"
  - DRUPAL_TI_WEBSERVER_URL="http://127.0.0.1"
  - DRUPAL_TI_WEBSERVER_PORT="8080"
  - DRUPAL_TI_SIMPLETEST_ARGS="--verbose --color --concurrency 4 --url $DRUPAL_TI_WEBSERVER_URL:$DRUPAL_TI_WEBSERVER_PORT"
  - DRUPAL_TI_BEHAT_DIR="./tests/behat"
  - DRUPAL_TI_BEHAT_ARGS=""
  - DRUPAL_TI_BEHAT_YML="behat.yml.dist"
  - DRUPAL_TI_BEHAT_SCREENSIZE_COLOR="1280x1024x16"
  - DRUPAL_TI_BEHAT_SELENIUM_VERSION="2.44"
  - DRUPAL_TI_BEHAT_DRIVER="phantomjs"
  - DRUPAL_TI_BEHAT_BROWSER="firefox"
  - DRUPAL_TI_PHPUNIT_ARGS=""
  - DRUPAL_TI_COVERAGE="satooshi/php-coveralls:0.6.*"
  - DRUPAL_TI_COVERAGE_FILE="build/logs/clover.xml"
  - DRUPAL_TI_DRUSH_VERSION="drush/drush:8.0.5"
  matrix:
  - DRUPAL_TI_RUNNERS="simpletest"
mysql:
  database: drupal_travis_db
  username: root
  encoding: utf8
before_install:
- composer self-update
- cd ./tests
- composer global require "lionsad/drupal_ti:dev-master"
- drupal-ti before_install
install:
- drupal-ti install
before_script:
- drupal-ti --include before.sh
script:
- drupal-ti script
after_script:
- drupal-ti after_script
notifications:
  email: true
  slack:
    secure: ac+ho2PldY4fj4ZTCA3JkIhC0WdHFDR5/aQfoehF42l8U1ugdw6Zvq+VhrCgkX1CAp77YvLWjIzU6HXIQuOS/YlPJ6NzRtfruoct22RBzpqoCNPEvUYRTdQnAuGuxtkCmRIHpfVIy6SVndgJ09DXK6pZjCF4dD3gzOZ2DPQzKDcAYtUR7Aafp9/Dg5MZ7uKtGtn9d67yeXLnrRNU1DBh+GIUaELEpDHDQ3l6tHko9d8I55Sna7G/+jAKjsuwEhAHBrkS6pGU7O7zsgLiyCO0xcNQkQnUbzodSRB3asp392BDhlsSr5h1qhEmZWyFA6z4vVrzif2P9+tbnAYK2hxkVhFKkUY6OzqCK+3nukx1ElQ25JMmaCeCc7SQToh3x/aHWrQSe3fiqw4VZA4bj0cciW81sAQE+XLWxIoIePI+8Evy3CGkj82U49wmpkVsyo1YZdnF6JcwLo+TkKy3bLonvwKOI7eP9aBxJ5Fx3kGx0js0KaE2ehL0xnyO8hAS30TJgGQz0RnvK1tpWctuqSPY5kMNyla46Y4crEQvkWhw7HKOEI57pGR8nt+aNiFIAF9BOlbjx6ECeIa/kx32b2imgaUQUEOmF2ZOSY7L2jbeaGDiBnjXd23wOXeHmJuDaxGcPFoqi7XXcu/wsRzglaQ282UTRr/9oYZSIVpvFpItV9o=
