<?php

/**
 * @file
 * (Un)installation functions for SAS Views RSS: DC Elements module.
 */

/**
 * Implements hook_install().
 */
function sas_views_rss_dc_install() {
  cache_clear_all('sas_views_rss:', 'cache_views', TRUE);
}

/**
 * Implements hook_uninstall().
 */
function sas_views_rss_dc_uninstall() {
  if (db_table_exists('cache_views')) {
    cache_clear_all('sas_views_rss:', 'cache_views', TRUE);
  }
}
